### ISSUE TITLE
Error alerts op de staging.adrez.cloud naar een slack-kanaal/logly

### ISSUE THREAD

**Issue by emcultuur** [emcultuur/adrez-import#3]
ik wil graag de errors naar een SLACK kanaal of LOGLY sturen;
Waar vind ik docu?

**Comment by toxus** [comment]
Documentatie staat:
https://github.com/emcultuur/logger.git

**Comment by emcultuur** [comment]
Dank je, ik kan dit volgen, maar hoe geef ik dit aan bij een customer.json gebruiker?

**Comment by emcultuur** [comment]
helemaal gelukt in de IMPORT-kant.
Puzzel nog verder over de API-meldingen
